apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ksnkstn/order-service
          env:
            - name: REDIS_HOST
              value: "redis-service"

          livenessProbe:
            exec:
              command: ["python", "-c", "import sys; sys.exit(0)"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            exec:
              command: ["python", "-c", "import sys; sys.exit(0)"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3